arb-dir: assets/translation
template-arb-file: en.arb
output-localization-file: app_localizations.dart
output-class: GTKLocalizations
nullable-getter: false
use-deferred-loading: true
synthetic-package: false
output-dir: lib/src/gen
