name: gtk_window
description: A package that add some missing gtk4 windowing features to flutter.
repository: https://github.com/helpis-software/gtk_window
version: 0.1.0+3
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  handy_window: ^0.3.1
  hotkey_manager: ^0.1.7
  intl: ^0.18.0
  utilities:
    path: ../../../../../utilities
  context_menu:
    path: ../../../context_menu
  universal_io: ^2.2.0
  window_manager: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
