name: gtk_window
description: A package that add some missing gtk4 windowing features to flutter.
repository: https://github.com/helpisdev/gtk_window
version: 0.3.1+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  breakpoints_utilities:
    path: packages/resizable_text/packages/breakpoints_utilities
  context_menu:
    path: packages/context_menu
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  handy_window: ^0.3.1
  hotkey_manager: ^0.1.8
  intl: ^0.18.1
  resizable_text:
    path: packages/resizable_text
  universal_io: ^2.2.2
  window_manager: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  melos: ^3.1.1

dependency_overrides:
  collection: ^1.18.0
  intl: ^0.18.1
