name: gtk_window
description: A package that add some missing gtk4 windowing features to flutter.
repository: https://github.com/helpisdev/gtk_window
version: 0.1.2+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  adaptive_scaffold:
    git:
      url: https://github.com/helpisdev/adaptive_scaffold.git
      ref: main
  context_menu:
    git:
      url: https://github.com/helpisdev/context_menu.git
      ref: main
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  handy_window: ^0.3.1
  hotkey_manager: ^0.1.7
  intl: ^0.18.0
  universal_io: ^2.2.0
  utilities:
    git:
      url: https://github.com/helpisdev/utilities.git
      ref: main
  window_manager: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  melos: ^3.1.0
